# Generated by Django 4.2.2 on 2023-07-05 09:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buyers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(default=0), default=list, size=None),
        ),
        migrations.AddField(
            model_name='product',
            name='creator',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
