# Generated by Django 4.2.3 on 2023-07-30 18:32

from django.db import migrations, models
import mydjangoapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.IntegerField(default=0)),
                ('addDate', models.DateTimeField(default=mydjangoapp.models.current_datetime, verbose_name='date added')),
                ('sold', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='product_images/')),
            ],
        ),
    ]
