# Generated by Django 4.2.2 on 2023-06-29 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("mydjangoapp", "0002_product_adddate_product_sold"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="product_images/"
            ),
            preserve_default=False,
        ),
    ]
