DROP TABLE IF EXISTS urls;
DROP TABLE IF EXISTS ips;

CREATE TABLE urls(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    original_url TEXT NOT NULL,
    clicks INTEGER NOT NULL DEFAULT 0
    short_url TEXT NOT NULL
);


