import 'dart:ui';
import 'package:flutter/material.dart';
import '../core/utils/size_utils.dart';

String _appTheme = "primary";

/// Helper class for managing themes and colors.
class ThemeHelper {
  // A map of custom color themes supported by the app
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Changes the app theme to [_newTheme].
  void changeTheme(String _newTheme) {
    _appTheme = _newTheme;
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      colorScheme: colorScheme,
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: colorScheme.primary,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(
              24,
            ),
          ),
          shadowColor: appTheme.red8003f,
          elevation: 4,
        ),
      ),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          backgroundColor: colorScheme.onPrimary.withOpacity(1),
          shape: RoundedRectangleBorder(
            side: BorderSide(
              color: appTheme.gray500,
              width: 1,
            ),
            borderRadius: BorderRadius.circular(
              8,
            ),
          ),
        ),
      ),
      floatingActionButtonTheme: FloatingActionButtonThemeData(
        backgroundColor: appTheme.gray900,
      ),
      textTheme: TextTheme(
        bodyMedium: TextStyle(
          color: appTheme.gray500,
          fontSize: getFontSize(
            14,
          ),
          fontFamily: 'Metropolis',
          fontWeight: FontWeight.w400,
        ),
        bodySmall: TextStyle(
          color: appTheme.gray500,
          fontSize: getFontSize(
            11,
          ),
          fontFamily: 'Metropolis',
          fontWeight: FontWeight.w400,
        ),
        labelMedium: TextStyle(
          color: colorScheme.onPrimary.withOpacity(1),
          fontSize: getFontSize(
            11,
          ),
          fontFamily: 'Metropolis',
          fontWeight: FontWeight.w600,
        ),
        bodyLarge: TextStyle(
          color: appTheme.gray900,
          fontSize: getFontSize(
            16,
          ),
          fontFamily: 'Metropolis',
          fontWeight: FontWeight.w400,
        ),
        titleSmall: TextStyle(
          color: appTheme.gray900,
          fontSize: getFontSize(
            14,
          ),
          fontFamily: 'Metropolis',
          fontWeight: FontWeight.w500,
        ),
        titleMedium: TextStyle(
          color: appTheme.gray900,
          fontSize: getFontSize(
            16,
          ),
          fontFamily: 'Metropolis',
          fontWeight: FontWeight.w600,
        ),
        displayMedium: TextStyle(
          color: appTheme.gray900,
          fontSize: getFontSize(
            44,
          ),
          fontFamily: 'Metropolis',
          fontWeight: FontWeight.w600,
        ),
        headlineSmall: TextStyle(
          color: colorScheme.onPrimary.withOpacity(1),
          fontSize: getFontSize(
            24,
          ),
          fontFamily: 'Metropolis',
          fontWeight: FontWeight.w600,
        ),
        displaySmall: TextStyle(
          color: appTheme.gray900,
          fontSize: getFontSize(
            34,
          ),
          fontFamily: 'Metropolis',
          fontWeight: FontWeight.w700,
        ),
      ),
      visualDensity: VisualDensity.standard,
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    background: Color(0X87FFFFFF),
    error: Color(0X87FFFFFF),
    errorContainer: Color(0XFFF01F0E),
    inversePrimary: Color(0X87FFFFFF),
    inverseSurface: Color(0X87FFFFFF),
    onBackground: Color(0XFF2C2C2C),
    onError: Color(0XFF2C2C2C),
    onErrorContainer: Color(0X87FFFFFF),
    onInverseSurface: Color(0XFF2C2C2C),
    onPrimary: Color(0X87FFFFFF),
    onPrimaryContainer: Color(0XFF2C2C2C),
    onSecondary: Color(0XFF2C2C2C),
    onSecondaryContainer: Color(0X87FFFFFF),
    onSurface: Color(0XFF2C2C2C),
    onSurfaceVariant: Color(0X87FFFFFF),
    onTertiary: Color(0XFF2C2C2C),
    onTertiaryContainer: Color(0X87FFFFFF),
    outline: Color(0X87FFFFFF),
    outlineVariant: Color(0X87FFFFFF),
    primary: Color(0XFFDB3022),
    primaryContainer: Color(0X87FFFFFF),
    scrim: Color(0X87FFFFFF),
    secondary: Color(0X87FFFFFF),
    secondaryContainer: Color(0XFFF01F0E),
    shadow: Color(0X87FFFFFF),
    surface: Color(0X87FFFFFF),
    surfaceTint: Color(0X87FFFFFF),
    surfaceVariant: Color(0XFFF01F0E),
    tertiary: Color(0X87FFFFFF),
    tertiaryContainer: Color(0XFFF01F0E),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Amber
  Color get amberA400 => Color(0XFFFFCC00);
  // Black
  Color get black900 => Color(0XFF000000);
  // BlueGray
  Color get blueGray400 => Color(0XFF8E8E92);
  Color get blueGray40001 => Color(0XFF888888);
  // DeepPurple
  Color get deepPurple900 => Color(0XFF312280);
  // Gray
  Color get gray100 => Color(0XFFF6F6F6);
  Color get gray200 => Color(0XFFF0F0F0);
  Color get gray400 => Color(0XFFBEA8A8);
  Color get gray40000 => Color(0X00C4C4C4);
  Color get gray50 => Color(0XFFF9F9F9);
  Color get gray500 => Color(0XFF9B9B9B);
  Color get gray800 => Color(0XFF4F4F4F);
  Color get gray900 => Color(0XFF222222);
  Color get gray90001 => Color(0XFF350E12);
  // Green
  Color get green600 => Color(0XFF2AA952);
  // Indigo
  Color get indigo600 => Color(0XFF3B5998);
  Color get indigo900 => Color(0XFF151867);
  // Orange
  Color get orange300 => Color(0XFFFFBA48);
  // Redf
  Color get red8003f => Color(0X3FD32525);
  // Red
  Color get red900 => Color(0XFFBF180E);
  Color get red90001 => Color(0XFFB72222);
  Color get redA700 => Color(0XFFEB001B);
  // Yellow
  Color get yellow800 => Color(0XFFF79E1B);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
