# Generated by Django 4.2.2 on 2023-06-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.UUIDField()),
                ('name', models.TextField(max_length=50)),
                ('descr', models.TextField(max_length=400)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
