# Generated by Django 4.2.2 on 2023-06-27 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eCom', '0002_remove_product_id_alter_product__id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='_id',
            new_name='id',
        ),
    ]
